// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0jXc0rpuakQsiPx5mmH1nx5dTS-qtpng',
    appId: '1:145401318503:web:9ab09a6bf7b4f01147d8c2',
    messagingSenderId: '145401318503',
    projectId: 'todo-list-app-56204',
    authDomain: 'todo-list-app-56204.firebaseapp.com',
    storageBucket: 'todo-list-app-56204.firebasestorage.app',
    measurementId: 'G-BM6RZ1NQSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkwvv0zXUTokQ8opfi5WPKw4sOWMzCoJ0',
    appId: '1:145401318503:android:cebf7749593b469647d8c2',
    messagingSenderId: '145401318503',
    projectId: 'todo-list-app-56204',
    storageBucket: 'todo-list-app-56204.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgGZafp2cR9yz5-sbUrQoWq7heVHt_2aI',
    appId: '1:145401318503:ios:5905b3d1e3e4da9947d8c2',
    messagingSenderId: '145401318503',
    projectId: 'todo-list-app-56204',
    storageBucket: 'todo-list-app-56204.firebasestorage.app',
    iosBundleId: 'com.mianabdullah.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgGZafp2cR9yz5-sbUrQoWq7heVHt_2aI',
    appId: '1:145401318503:ios:5905b3d1e3e4da9947d8c2',
    messagingSenderId: '145401318503',
    projectId: 'todo-list-app-56204',
    storageBucket: 'todo-list-app-56204.firebasestorage.app',
    iosBundleId: 'com.mianabdullah.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0jXc0rpuakQsiPx5mmH1nx5dTS-qtpng',
    appId: '1:145401318503:web:f9d04dca96a6699447d8c2',
    messagingSenderId: '145401318503',
    projectId: 'todo-list-app-56204',
    authDomain: 'todo-list-app-56204.firebaseapp.com',
    storageBucket: 'todo-list-app-56204.firebasestorage.app',
    measurementId: 'G-WB8G7FPSEB',
  );
}
